name: Auto Generate OWID Chart Video

on:
  schedule:
    - cron: '0 12 * * *'  # every day at 12:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Run script to generate video
      run: python generate_video.py --metric life_expectancy --country "India"

    - name: Upload video
      uses: actions/upload-artifact@v4
      with:
        name: generated-video
        path: output/*.mp4
